MyBlog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  get 'careers' => 'pages#careers'
  get 'posts/films/new' => 'films#new'
  get 'posts/films/careers' => 'pages#careers'
  resources :posts do
    resources :films
  end
  resources :films do
    resources :posts
  end

end

MyBlog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MyBlog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

MyBlog/app/models/film.rb
class Film < ApplicationRecord
  has_many :links
  has_many :posts, through: :links
end

MyBlog/app/models/link.rb
class Link < ApplicationRecord
  belongs_to :post
  belongs_to :film
end

MyBlog/app/models/post.rb
class Post < ApplicationRecord
  has_many :links
  has_many :films, through: :links
  validates :title, presence: true, length: {minimum: 5}
end

MyBlog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

MyBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

MyBlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

MyBlog/app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  def index
    @film=Film.all
  end

  def new

  end

  def edit
    @film=Film.find(params[:id])
  end

  def show
    @film=Film.find(params[:id])
  end

  def create
    @film=Film.new(film_params)
    if(@film.save)
      redirect_to @film
    else
      render 'new'
    end
  end

  def destroy
    @film=Film.find(params[:id])
    @film.destroy
    redirect_to films_path
  end

  def update
    @film=Film.find(params[:id])
    if(@film.update(film_params))
      redirect_to @film
    else
      render 'edit'
    end
  end

  private
  def film_params
    params.require(:film).permit(:name, :director, :year, :actors, :discription)
  end
end

MyBlog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def careers
  end
end

MyBlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show,:index]
  def index
    @post=Post.all
  end

  def new
    @post=Post.new
  end

  def edit
    @post=Post.find(params[:id])
  end

  def show
    @post=Post.find(params[:id])
  end

  def create
    movies=params[:val]
    movies=movies.split("|")
    @post=Post.new(post_params)
    movies.size.times do |i|
      @film=Film.find_by_name(movies[i])
      @post.films << @film
    end
    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
      @post=Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  def update
    @post=Post.find(params[:id])
    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

MyBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

MyBlog/app/helpers/comments_helper.rb
module CommentsHelper
end

MyBlog/app/helpers/films_helper.rb
module FilmsHelper
end

MyBlog/app/helpers/pages_helper.rb
module PagesHelper
end

MyBlog/app/helpers/posts_helper.rb
module PostsHelper
end

MyBlog/app/views/films/edit.html.erb
<h2><%= t("Edit the film") %></h2>
<% if current_user.admin %>
<%= form_for :film, url: film_path(@film), method: :patch do |f|%>
  <p>
    <%= t("Name") %><br>
    <%= f.text_field(:name, {:class => 'form-control'}) %><br><br>
    <%= t("Director") %><br>
    <%= f.text_field(:director, {:class => 'form-control'}) %><br><br>
    <%= t("Year") %><br>
    <%= f.text_field(:year, {:class => 'form-control'}) %><br><br>
    <%= t("Actors") %><br>
    <%= f.text_field(:actors, {:class => 'form-control'}) %><br><br>
    <%= t("Slogan") %><br>
    <%= f.text_area(:discription, {:class => 'form-control'}) %><br><br>
  </p>
  <p>
    <%= f.submit(t('Save changes'),{:class => 'btn btn-primary'}) %><br>
  </p>
<%end%>
<% else %>
<h1>Not so easy</h1>
<% end %>

MyBlog/app/views/films/index.html.erb
<h1><%= t('Films') %></h1>
<% @film.each do |film| %>
  <p><h3><%= link_to film.name, film_path(film)%></h3></p>
<%end%>

MyBlog/app/views/films/new.html.erb
<h2><%= t("Add a film")%></h2>
<% if current_user.admin %>
<%= form_for :film, url: films_path do |f|%>
  <p>
    <%= t("Name") %><br>
    <%= f.text_field(:name, {:class => 'form-control'}) %><br><br>
    <%= t("Director") %><br>
    <%= f.text_field(:director, {:class => 'form-control'}) %><br><br>
    <%= t("Year") %><br>
    <%= f.text_field(:year, {:class => 'form-control'}) %><br><br>
    <%= t("Actors") %><br>
    <%= f.text_field(:actors, {:class => 'form-control'}) %><br><br>
    <%= t("Slogan") %><br>
    <%= f.text_area(:discription, {:class => 'form-control'}) %><br><br>
  </p>
  <p>
    <%= f.submit(t('Add'),{:class => 'btn btn-primary'}) %><br>
  </p>
<%end%>
<% else %>
<h1>Not so easy</h1>
<% end %>

MyBlog/app/views/films/show.html.erb
<h2><%= t("Name") %> :<%= @film.name %></h2><br>
<p>  <%= t("Year") %> :<%= @film.year %><p>
<p>  <%= t("Director") %> :<%= @film.director %><p>
<p>  <%= t("Actors") %> :<%= @film.actors %><p>
<p>  <%= t("Slogan") %> :<%= @film.discription %></p>
<hr>
<h4>  <%= t("Articles about this film") %></h4>
<% @film.posts.each do |post| %>
    <p><%= link_to post.title, post_path(post)%></p>
<% end %>
<% if current_user.admin %>
<%= link_to 'Edit', edit_film_path(@film), :class => 'btn btn-primary'%>
<%= link_to 'Delete the film', film_path(@film), method: :delete, :class => 'btn btn-danger'%>
<% end %>

MyBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-dark border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal text-primary">
    <%= link_to 'Cinema blog', root_path, :class => 'text-primary'%>
    <% if I18n.locale == :ru %>
      <%= link_to 'en', {locale: :en}, :class => 'btn btn-primary'%>
    <% end %>
    <% if I18n.locale == :en %>
      <%= link_to 'рус', {locale: :ru}, :class => 'btn btn-primary'%>
    <% end %>
  </h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <span class="p-2 text-primary"><%= link_to t('Articles'), root_path%></span>
    <span class="p-2 text-dark"><%= link_to t('Films'), films_path%></span>
    <% if current_user %>
    <% if current_user.admin %>
    <span class="p-2 text-dark"><%= link_to t('New Article'), new_post_path%></span>
    <% end %>
    <% if current_user.admin %>
    <span class="p-2 text-dark"><%= link_to t('New Film'), 'films/new'%></span>
    <% end %>
    <% end %>
    <% if current_user %>
    <span class="p-2 text-dark"><%= link_to t('Careers'), 'careers'%></span>
    <% end %>
  </nav>
  <% if current_user %>
  <span class="btn btn-outline-primary" href="#"><%= link_to 'Sign out', destroy_user_session_path, method: :delete%></span>
  <% else %>
  <span class="btn btn-outline-primary" href="#"><%= link_to 'Sign in', new_user_session_path%></span>
  <% end %>

</div>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

MyBlog/app/views/pages/careers.html.erb
<h2>Get the fuck out of here we don't need you</h2>

MyBlog/app/views/posts/edit.html.erb
<h1><%= t("Edit the article") %></h1>
<% if current_user.admin %>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
<%if @post.errors.any? %>
  <strong>В названии статьи должно быть больше пяти смволов</strong>
<%end%>
<p>
  <%= t("Title") %><br>
  <%= f.text_field(:title, {:class => 'form-control'}) %><br><br>
  <%= t("Body") %><br>
  <%= f.text_area(:body, {:class => 'form-control'}) %><br>
  <%= f.submit('Add',{:class => 'btn btn-primary'}) %><br>
</p>
<% end %>
<% else %>
<h1>Not so easy</h1>
<% end %>

MyBlog/app/views/posts/index.html.erb
<h1><%= t("Main page")%></h1>
<% @post.each do |post| %>
  <p><h3><%= link_to post.title, post_path(post)%></h3></p>
<%end%>

MyBlog/app/views/posts/new.html.erb
<h1><%= t("Add an article")%></h1>
<% if current_user.admin %>
<%= form_for :post, url: posts_path do |f| %>
<%if @post.errors.any? %>
  <strong>В названии статьи должно быть больше пяти смволов</strong>
<%end%>
<p>
  <%= t("Title") %><br>
  <%= f.text_field(:title, {:class => 'form-control'}) %><br><br>
  <%= t("Body") %><br>
  <%= f.text_area(:body, {:class => 'form-control'}) %><br>
  <%= text_field_tag(:val) %> <br/><br/>
  <%= f.submit('Add',{:class => 'btn btn-primary'}) %><br>
</p>
<% end %>
<% else %>
<h1>Not so easy</h1>
<% end %>

MyBlog/app/views/posts/show.html.erb
<h2><%= @post.title %></h2><br>
<p><%= @post.body %><p>
<hr>
<h4><%= t("Films related to the article") %></h4>
<% @post.films.each do |film| %>
  <p><%= link_to film.name, film_path(film)%></p>
<% end %>
<% if current_user.admin %>
<%= link_to t('Edit'), edit_post_path(@post), :class => 'btn btn-primary'%>
<%= link_to t('Delete'), post_path(@post), method: :delete, :class => 'btn btn-danger'%>
<% end %>